keys:
  - &rune ECB0BFADD67F510503672D8AA22733919C497E19
  - &laptop age1wcpvuecelfyecsmjra753k83702xd5tqwkz8yq3kj76ac26zucjsq9t005

creation_rules:
  - path_regex: ^secrets.yml$
    key_groups:
    - age: [*laptop]
      pgp: [*rune]
